name: json_form
description: A Flutter widget capable of using JSON Schemas to build and customize forms.
version: 0.0.1+1
repository: https://github.com/juancastillo0/json_form
homepage: https://juancastillo0.github.io/json_form/
issue_tracker: https://github.com/juancastillo0/json_form/issues
screenshots:
  - description: >
      An example of a form built using JSON Schema with multiple primitive types. 
      You can interact with it in the deploy Github Page.
    path: images/json_form_primitives_examples_page.png
topics:
  - json-schema
  - forms
  - validators
  - inputs
  - json

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  extended_masked_text: ^3.0.1
  cross_file: ^0.3.4+1
  validators: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.6.1
  json_form_example:
    path: example